global_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 3.0
  publish_frequency: 1.0
  transform_tolerance: 0.5

  # Với SLAM động, static_map thường không có /map_updates; vẫn dùng được
  static_map: true

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
